[package]
name = "tamron-lens-control"
version = "0.1.0"
edition = "2024"
description = "Stateless Linux CLI and Rust library for configuring compatible Tamron lenses"
license = "GPL-3.0-or-later"
readme = "README.md"

[[bin]]
name = "tlc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
crc = "3.4.0"
log = "0.4.33"
serialport = "4.9.0"
thiserror = "2.0.19"
